server {
    listen 80;

    location /api/tenant/ {
        proxy_pass http://tenant-service:8000/;
    }

    location /api/onboarding/ {
        proxy_pass http://onboarding-service:8001/;
    }

    location /api/payroll/ {
        proxy_pass http://payroll-service:8002/;
    }

    location /api/users/ {
        proxy_pass http://user-service:8003/;
    }

    location /api/reporting/ {
        proxy_pass http://reporting-service:8004/;
    }

    location /health {
        return 200 'ok';
    }
}
